word_list = (
    'ant baboon badger bat bear beaver camel cat clam cobra cougar '
    'coyote crow deer dog donkey duck eagle ferret fox frog goat '
    'goose hawk lion lizard llama mole monkey moose mouse mule newt '
    'otter owl panda parrot pigeon python rabbit ram rat raven '
    'rhino salmon seal shark sheep skunk sloth snake spider '
    'stork swan tiger toad trout turkey turtle weasel whale wolf '
    'wombat zebra apple banana cherry orange grape melon lemon '
    'peach berry tomato bread cheese pizza burger pasta coffee '
    'butter honey sugar pepper chair table window mirror candle '
    'blanket pillow basket hammer jacket spring summer autumn '
    'winter cloud shadow thunder forest desert valley doctor '
    'lawyer police pilot chef artist actor writer singer airport '
    'bakery school market castle palace museum garden harbor '
    'station rocket subway glider bicycle scooter cruiser tractor '
    'trailer balloon airship guitar violin trumpet piano flute '
    'drum symbol whistle rhythm melody astronaut architect '
    'billionaire carpenter detective scientist engineer avalanche '
    'blizzard hurricane tornado volcano earthquake wildfire '
    'adventure beautiful brilliant challenge dangerous dinosaur '
    'element fantastic galaxy horizon illusion jealousy kingdom '
    'labyrinth mystery nostalgia odyssey phantom quantum rainbow '
    'sapphire triumph universe luxury sphinx pharaoh mummy '
    'pyramid zombie vampire ghost monster goblin wizard jigsaw '
    'matrix gossip quartz zigzag balloon bicycle blanket breeze '
    'bucket camera candle canyon canvas carpet castle cavern '
    'clover copper cosmic cradle crater crayon crystal dagger '
    'dancer danger dawn eclipse engine fabric falcon feather '
    'fossil frozen garden garlic genius glacier glider goblin '
    'gothic gravel guitar harbor helmet herbal hollow hunter '
    'iceberg infant island jacket jaguar jester jungle kettle '
    'knight lantern legacy legend leopard lizard locker lunar '
    'magnet marble meadow melody memory mentor meteor mirror '
    'monkey monster mosaic museum mutant napkin nebula needle '
    'nestle nomad novel nugget orchid oxygen oyster paddle '
    'palace pancake panther parade parrot pebble penguin phantom '
    'phoenix pickup pigeon pillow planet plastic pocket poetry '
    'portal potion pottery powder prince prison puppet puzzle '
    'pyramid quarry quartz quasar quiver rabbit radar radiant '
    'raindrop ranger rattle raven record rescue ribbon riddle '
    'ritual rocket runway saddle safari sailor salmon salute '
    'sample sandal sapphire satin saucer scarab scenic scholar '
    'school scooter scorch scriba scrypt scroll sculpt search '
    'season secret seeker sensor shadow shaman shield shiver '
    'shrine shuttle signal silver sketch skiier skunk skyline '
    'slacker sleeve slogan smooth sneeze sniper soccer solar '
    'soldier solemn sonar sorrow source spark sphere spider '
    'spiral spirit splash sponge spring sprint sprite spur '
    'spyglass stable stadium statue steady stream street stress '
    'strike studio submit subway sudden summer summit summon '
    'sunset superb supply surface switch sword symbol tablet '
    'tackle talent tango target tattoo tavern teapot temple '
    'tenant tender tennis terror theory thesis thief thunder '
    'ticket tiger timber timing tinker tissue titan toast '
    'tobacco token tomato tongue topic torch tornado towing '
    'toxic traces tractor traffic tragic trail trailer train '
    'treat treaty trench trend tribal tribute trick trinity '
    'tripod triumph trophy tropic truck trumpet trunk trust '
    'truth tube tulip tumble tunnel turkey turnip turtle '
    'tutor twilight twins twist tycoon typhoon tyrant ulcer '
    'umber umbrella umpire uncle uncoil under unfold unicorn '
    'union unique unit universe updo uphill upload uproar '
    'uproot upset upside upward urban urchin urgent urinal '
    'urn usage usher utopia vacant vacuum vagrant vague '
    'valet valley valor value valve vampire vanish vanity '
    'vapor vector velvet vendor venom venture verbal verdict '
    'verge verify verse vessel vest veteran veto viaduct '
    'vial vibe vibrant vicar victim victor video view '
    'vigil viking villa village vine vintage vinyl viola '
    'violet violin viper viral virgin virtue virus visa '
    'viscount vision visit visor vista visual vital vitamin '
    'vivid vixen vocal vodka vogue voice void volcano '
    'vortex voter voting vouch vowel voyage vulcan vulgar '
    'vulture wagon waist waiter waiver wallet walnut walrus '
    'waltz wampum wander wanted warble warden warder warm '
    'warmth warn warp warrant warrior warship wart wash '
    'washer wasp waste watch water wave wax wealth '
    'weapon weasel weather weave web wedding wedge weeds '
    'weekly weep weigh weight weird welcome weld welfare '
    'well west whale wharf wheat wheel wheeze whelp '
    'while whim whimper whine whip whirl whisk whiskey '
    'whisper whistle white whole whore whorl wicked wicker '
    'wicket wide widow width wield wife wigwam wild '
    'willow willow wilting wince winch wind window windy '
    'wine wing wink winner winter wipe wire wisdom '
    'wise wish witch withers witness witty wizard wobble '
    'woe wolf woman womb wombat wonder wood wool '
    'word work world worm worry worse worship worst '
    'worth worthy wound woven wrap wrath wreath wreck '
    'wrench wrestle wright wring wrinkle wrist write writer '
    'wrong wrought wrung wryly xebec xenon xerox '
    'xylem yacht yahoo yak yam yank yankee yard '
    'yarn yawn year yearn yeast yell yellow yelp '
    'yeoman yes yesterday yeti yield yodel yoga yogurt '
    'yoke yolk yonder yore young youngster youth '
    'yoyo yucca yummy zany zeal zealot zebra '
    'zenith zephyr zero zest zesty zigzag zinc '
    'zing zipper zircon zither zodiac zombie zone '
    'zonk zoom zucchini'
).split()